site_name: Certificate Identity Declaration SDK for Citrix Workspace app 1808 for Linux
site_description: Reference guide for Certificate Identity Declaration SDK for Citrix Workspace app 1808 for Linux
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
     anchorlink: true

pages:
  - Home: index.md
